# Docker produccion o stage
FROM node:14.3.0

ENV MONGO_URL mongodb://host.docker.internal/cart
ENV AUTH_SERVICE_URL http://host.docker.internal:3000
ENV CATALOG_SERVICE_URL http://host.docker.internal:3002
ENV RABBIT_URL amqp://host.docker.internal

WORKDIR /app
RUN curl -L https://github.com/nmarsollier/ecommerce_cart_node/tarball/master | tar xz --strip=1
RUN npm install --silent
RUN npm run build

# Puerto  Cart Service
EXPOSE 3003

CMD cd dist; node server.js
